version: '3.9'
services:
  
  # Section: Backend container service
  # backend service will work depends on database container service

  # Section: Frontend container service
  # frontend will work depends on backend container service

  # Section: Database Service
  # postgres with PgAdmin
  db_postgres:
    image: postgres:latest
    restart: always
    environment: 
      POSTGRES_DATABSE: f2xhotel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGTRES_ROOT_PASSWORD:  
    volumes:
      - .db_data:/var/lib/postgres/data
    ports:
      - 5432:5432
  
  # pgadmin container service work depends on postgres container service (db_postgres)
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=psinthorn@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=adminx
    ports:
      - 5050:80
    restart: always
    volumes:
      - pgadmin:/root/.pgadmin
    depends_on:
      - db_postgres

# Section: Volumn Data
volumes:
  .db_data:
  pgadmin:
      
    