version: '3.9'

# Request: 
# need to add frontend container to complete example for full stack environment development
#

services: 

  # backend: example
  #   # build image from this directory with default file (Dockerfile)
  #   # *if you user another name of Dockerfile then you need to replace file name 
  #   build: .
  #   ports:
  #     # expose_port : container_port
  #     - 8000:3000

  #   volumes: 
  #     # if any changed on both of current working and /app directory will be copy to each immediately  
  #     - .:/app

  #   # backend service will start if database is up and running completely 
  #   depends_on: 
  #     - db_mysql
  #     - redis

  # Section service database section
  # mysql container service
  db_mysql:
    image: mysql:5.7.22
    container_name: db_mysql
    restart: always
    ports:
      - 33066:3306
    environment: 
      MYSQL_DATABASE: database_name
      MYSQL_USER: root
      MYSQL_PASWORD: root
      MYSQL_ROOT_PASSWORD: root 
    volumes: 
      - dbdata:/var/lib/mysql

  # phpmyadmin container service
  # this service is work depends on mysql container service (db_mysql)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    restart: always
    ports:
      - 8081:80
    links:
      - db_mysql
    environment:
      PMA_HOST: db_mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    
    depends_on:
      - db_mysql

  # redis container service
  redis:
    image: redis:latest
    ports:
      - 6378:6379
volumes:
  dbdata: