version: '3.9'

services:
  # Section service database section
  # mysql container service
  db_mysql:
    image: mysql:5.7.22
    container_name: db_mysql
    restart: always
    ports:
      - 33066:3306
    environment: 
      MYSQL_DATABASE: database_name
      MYSQL_USER: root
      MYSQL_PASWORD: root
      MYSQL_ROOT_PASSWORD: root 
    volumes: 
      - dbdata:/var/lib/mysql
    

  # phpmyadmin container service
  # this service is work depends on mysql container service (db_mysql)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    restart: always
    ports:
      - 8081:80
    links:
      - db_mysql
    environment:
      PMA_HOST: db_mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    depends_on:
      - db_mysql
volumes:
  dbdata: