version: '3'
# services:
  # container name 
    # image:
    # environment: 
      # - env 
    # ports: 
      # - 8080:80
    # volumes: 
    # depends_on:
      # - datatabase 
services:
  iacc:
    image: 
    environment:
    ports:
      - 8080:80

  db_mysql:
    image: mysql

  phpmyadmin:
    image:
    ports:
     - 33061:3306
    environment:
    volumes:
      - mysql_data:/var/lib/mysql
      
volumes:
  mysql_data:
    driver: local
 